### ISSUE TITLE
What about test262?

### ISSUE THREAD

**Issue by mathiasbynens** [angus-c/es6-tests#3]
Why a separate project instead of contributing to https://github.com/tc39/test262? This is a genuine question, and I can think of many possible answers. For one, both the code and the file organization in this repository seems much cleaner/clearer IMHO, making it easier to contribute tests. But since this is probably a Frequently Asked Question™, how about adding an entry to the README?

**Comment by angus-c** [comment]
see also https://github.com/angus-c/es6-tests/issues/1 :)

I'm certainly not trying to compete with test262, which will (of course) always be better than this. This is purely for my own education. I'm writing an all-ES6 book and want to make sure I have a thorough understanding of the new spec.

**Comment by angus-c** [comment]
FAQ added

**Comment by mathiasbynens** [comment]
Apologies for not searching through the closed issues first.
